name: "Auto Code Review"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  ai-pr-review:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoreview') || github.event.label.name == 'autoreview' }}
    runs-on:
      labels: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Install dependencies
        run: |
          ls -la
          apt update && apt install git gawk -y
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: samarthiesoft/ai-pr-reviewer@main
        env:
          GIT_REPO_PATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
