name: "Auto Code Review"

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  ai-pr-review:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoreview') && github.event.pull_request.state == "open" }}
    runs-on:
      labels: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install git gawk -y
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: samarthiesoft/ai-pr-reviewer@develop
        env:
          GIT_REPO_PATH: $GITHUB_WORKSPACE/.git
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
