name: "Auto Code Review"

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  ai-pr-review:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoreview') || github.event.label.name == 'autoreview' }}
    runs-on:
      labels: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install git -y
      # - name: Delete existing repo
      #   run: |
      #     cd $GITHUB_WORKSPACE && rm -rf *  && rm -rf .git*
      #     ls -al
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug
        run: |
          ls -al
          cd .git && ls -al && cd ..
          git diff 73a23b3ff7f31ed9c6e130899e2a3221fe7becfa..9eb502d33d1adeb5bc9a6e615fc077110bdd1247
      # - uses: samarthiesoft/ai-pr-reviewer@main
      #   env:
      #     GIT_REPO_PATH: $GITHUB_WORKSPACE
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
