name: AI PR Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  ai_pr_review:
    if: ${{ github.event.label.name == 'ai-review' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: samarthiesoft/ai-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
