name: GPTcode-reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: GPT code review Action
        uses: PierreGode/GPTcode-reviewer@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
